"""
AEAF HTML dashboard generator.

Generates a standalone HTML audit dashboard.
"""

from __future__ import annotations

from datetime import datetime
from html import escape
from pathlib import Path

from ..models import RepositoryModel


class HTMLReportGenerator:
    """
    Generate standalone HTML reports.
    """

    def generate(
        self,
        repository: RepositoryModel,
    ) -> str:
        """
        Generate HTML dashboard.
        """

        stats = repository.statistics

        complexity = sorted(
            repository.complexity,
            key=lambda item: item.score,
            reverse=True,
        )[:10]

        documentation = repository.documentation

        complexity_rows = "".join(
            f"""
            <tr>
                <td>{index}</td>
                <td>{escape(item.name)}</td>
                <td>{escape(item.kind)}</td>
                <td>{item.score}</td>
            </tr>
            """
            for index, item in enumerate(
                complexity,
                start=1,
            )
        )

        documentation_rows = "".join(
            f"""
            <tr>
                <td>{escape(name)}</td>
                <td>
                    <div class="progress">
                        <div class="bar"
                             style="width:{data.get('coverage',0)}%">
                        </div>
                    </div>
                    {data.get('coverage',0)}%
                </td>
            </tr>
            """
            for name, data in documentation.items()
            if isinstance(data, dict)
        )

        return f"""
<!DOCTYPE html>
<html>

<head>

<meta charset="utf-8">

<title>
AEAF Repository Audit Dashboard
</title>


<style>

body {{
    font-family: Arial, sans-serif;
    margin: 40px;
    background: #f5f5f5;
}}


h1 {{
    margin-bottom: 5px;
}}


.card {{
    background: white;
    border-radius: 8px;
    padding: 20px;
    margin: 15px 0;
}}


.cards {{
    display: grid;
    grid-template-columns:
    repeat(auto-fit,minmax(180px,1fr));
    gap: 15px;
}}


.metric {{
    background: white;
    padding: 20px;
    border-radius: 8px;
}}


.metric h2 {{
    margin: 0;
}}


table {{
    width:100%;
    border-collapse: collapse;
}}


th, td {{
    padding: 10px;
    border-bottom: 1px solid #ddd;
}}


.progress {{
    background:#eee;
    height:20px;
    border-radius:10px;
    overflow:hidden;
}}


.bar {{
    height:100%;
    background:#4caf50;
}}


footer {{
    margin-top:30px;
    color:#666;
}}

</style>

</head>


<body>


<h1>
AEAF Repository Audit Dashboard
</h1>

<p>
Generated:
{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
</p>


<div class="card">

<h2>
Repository
</h2>

<p>
{escape(repository.metadata.name)}
</p>

</div>



<div class="cards">


<div class="metric">
<h2>{stats.source_files}</h2>
<p>Source Files</p>
</div>


<div class="metric">
<h2>{stats.modules}</h2>
<p>Modules</p>
</div>


<div class="metric">
<h2>{stats.classes}</h2>
<p>Classes</p>
</div>


<div class="metric">
<h2>{stats.functions}</h2>
<p>Functions</p>
</div>


<div class="metric">
<h2>{stats.methods}</h2>
<p>Methods</p>
</div>


<div class="metric">
<h2>{stats.imports}</h2>
<p>Imports</p>
</div>


</div>



<div class="card">

<h2>
Dependency Graph
</h2>

<p>
Edges:
<strong>
{len(repository.dependency_graph.edges)}
</strong>
</p>

</div>



<div class="card">

<h2>
Complexity Hotspots
</h2>


<table>

<tr>
<th>#</th>
<th>Name</th>
<th>Kind</th>
<th>Score</th>
</tr>

{complexity_rows}

</table>

</div>




<div class="card">

<h2>
Documentation Coverage
</h2>


<table>

<tr>
<th>Area</th>
<th>Coverage</th>
</tr>

{documentation_rows}

</table>

</div>



<footer>

Generated by Athena Engineering Audit Framework (AEAF)

</footer>


</body>

</html>
"""

    def save(
        self,
        repository: RepositoryModel,
        output: Path,
    ) -> None:
        """
        Save HTML dashboard.
        """

        output.write_text(
            self.generate(repository),
            encoding="utf-8",
        )