"""
AEAF Markdown report generator.

Converts RepositoryModel audit results into
a human-readable Markdown report.
"""

from __future__ import annotations

from pathlib import Path

from ..models import RepositoryModel


class MarkdownReportGenerator:
    """
    Generate Markdown audit reports.
    """

    def generate(
        self,
        repository: RepositoryModel,
    ) -> str:
        """
        Generate Markdown report content.
        """

        stats = repository.statistics

        lines = []

        lines.append(
            "# AEAF Repository Audit Report"
        )

        lines.append("")

        lines.append(
            "## Repository"
        )

        lines.append("")

        lines.append(
            f"- Name: `{repository.metadata.name}`"
        )

        lines.append(
            f"- Path: `{repository.metadata.root}`"
        )


        lines.append("")

        lines.append(
            "## Statistics"
        )

        lines.append("")

        lines.append(
            "| Metric | Value |"
        )

        lines.append(
            "|---|---:|"
        )

        statistics = {
            "Source Files": stats.source_files,
            "Packages": stats.packages,
            "Modules": stats.modules,
            "Classes": stats.classes,
            "Functions": stats.functions,
            "Methods": stats.methods,
            "Imports": stats.imports,
            "Findings": stats.findings,
        }

        for name, value in statistics.items():

            lines.append(
                f"| {name} | {value} |"
            )


        lines.append("")

        lines.append(
            "## Dependency Graph"
        )

        lines.append("")

        lines.append(
            f"Edges: **{len(repository.dependency_graph.edges)}**"
        )


        lines.append("")

        lines.append(
            "## Complexity Hotspots"
        )

        lines.append("")

        lines.append(
            "| Rank | Name | Kind | Score |"
        )

        lines.append(
            "|---:|---|---|---:|"
        )

        hotspots = sorted(
            repository.complexity,
            key=lambda item: item.score,
            reverse=True,
        )[:10]

        for index, item in enumerate(
            hotspots,
            start=1,
        ):

            lines.append(
                f"| {index} | {item.name} | "
                f"{item.kind} | {item.score} |"
            )


        lines.append("")

        lines.append(
            "## Documentation Coverage"
        )

        lines.append("")

        documentation = repository.documentation

        lines.append(
            "| Area | Coverage |"
        )

        lines.append(
            "|---|---:|"
        )

        for name, data in documentation.items():

            if isinstance(data, dict):

                lines.append(
                    f"| {name} | "
                    f"{data.get('coverage', 0)}% |"
                )


        lines.append("")

        lines.append(
            "---"
        )

        lines.append(
            "Generated by Athena Engineering Audit Framework (AEAF)."
        )

        return "\n".join(
            lines,
        )


    def save(
        self,
        repository: RepositoryModel,
        output: Path,
    ) -> None:
        """
        Save Markdown report to disk.
        """

        report = self.generate(
            repository,
        )

        output.write_text(
            report,
            encoding="utf-8",
        )